//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Year { get; set; }
        public int Genre_Id { get; set; }
        public int Distributor_Id { get; set; }
        public int Creator_Id { get; set; }
        public Nullable<int> RankCount { get; set; }
        public Nullable<int> RankOveral { get; set; }
        public int DeviceId { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Distributors Distributors { get; set; }
        public virtual Creators Creators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual Device Device { get; set; }
    }
}
