//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposedGames
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Year { get; set; }
        public int Genre_Id { get; set; }
        public int Distributor_Id { get; set; }
        public int Creator_Id { get; set; }
        public Nullable<int> RankCount { get; set; }
        public Nullable<int> RankOveral { get; set; }
        public int DeviceId { get; set; }
        public int State_Id { get; set; }
        public string ProposedBy { get; set; }
    }
}
