//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reviews()
        {
            this.FavouriteReviews = new HashSet<FavouriteReviews>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime Created_At { get; set; }
        public string User_Id { get; set; }
        public int Game_Id { get; set; }
        public int UserRank { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> ReviewPoints { get; set; }
        public string Temporary { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavouriteReviews> FavouriteReviews { get; set; }
    }
}
