//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrustLevels
    {
        public int Id { get; set; }
        public string TrustLevel { get; set; }
        public int System_Id { get; set; }
        public string TrustLevel_cz { get; set; }
    }
}
